/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tesis_rhti;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CD
 */
public class VentanaBusquedaCandidatos extends javax.swing.JFrame {

    /**
     * Creates new form CandidatosInfo
     */

    public VentanaBusquedaCandidatos() {
        initComponents();
//        mostrarDatos(0);     
        setLocationRelativeTo(null);
        setResizable(false);
        txtIdPerfilIdoneo.setEditable(false);
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);

    }


    void mostrarDatosInicio(int idPerfilIdoneo) {
     Conexion c = new Conexion();
     Connection con = c.getConexion();
     String sql_1 = "SELECT * FROM Perfiles_idoneos_general WHERE Id_perfil_idoneo ='"+ idPerfilIdoneo +"'";
     int numReg = 0;
                   
     try {            
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(sql_1);

             
         while(rs.next())
         {        
          txtIdPerfilIdoneo.setText(String.valueOf(rs.getInt(1)));
          jTextField1.setText(rs.getString(2));
          jTextField2.setText(rs.getString(3).trim());
          jTextField3.setText(String.valueOf(rs.getDate(4)));
          jTextField4.setText(String.valueOf(rs.getDate(5)));
          jTextField5.setText(rs.getString(6));
          
          numReg ++;
         }   
       
         if (numReg == 0)
            {
            JOptionPane.showMessageDialog(null, "No se encontraron resultados.\nIntente nuevamente");     
            }
        
        rs.close();
        con.close();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaBusquedaCandidatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        c.cerrarConexion();
        mostrarDatos(idPerfilIdoneo);
        
    }
    


    void mostrarDatos(int idPerfilIdoneo) {
       
     DefaultTableModel tablaDinamica = new DefaultTableModel(); 

     tablaDinamica.addColumn("ID CANDIDATO");
     tablaDinamica.addColumn("ID PERFIL IDÓNEO");
     tablaDinamica.addColumn("DIST. HAMMING");
     tablaDinamica.addColumn("DIST. EUCLIDIANA");
     tablaDinamica.addColumn("DIST. RUSSEL Y RAO");
     tablaDinamica.addColumn("DIST. JACCARD");
     tablaDinamica.addColumn("FECHA BUSQUEDA");
     tablaDinamica.addColumn("FECHA VIGENCIA");
     tablaDinamica.addColumn("ESTATUS");
     
     tableCandidatos.setModel(tablaDinamica);

     Conexion c = new Conexion();
     Connection con = c.getConexion();
     String sql_1 = "SELECT * FROM Perfiles_candidatos_general WHERE Id_perfil_idoneo ='"+ idPerfilIdoneo +"'";
     String [] array = new String[9];
     int numReg = 0;
                    
     try {            
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(sql_1);

             
         while(rs.next())
         {        

          array[0]= rs.getString(1);
          array[1]= String.valueOf(rs.getInt(2));         
          array[2]= String.valueOf(rs.getDouble(3));
          array[3]= String.valueOf(rs.getDouble(4));
          array[4]= String.valueOf(rs.getDouble(5));
          array[5]= String.valueOf(rs.getDouble(6));                 
          array[6]= String.valueOf(rs.getDate(7));
          array[7]= String.valueOf(rs.getDate(8));         
          array[8]= rs.getString(9);
 
          tablaDinamica.addRow(array);           
          numReg ++;
         }   
       
         if (numReg == 0)
            {
            JOptionPane.showMessageDialog(null, "No se encontraron resultados.\nIntente nuevamente");     
            }
        
        rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaBusquedaCandidatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        c.cerrarConexion();


    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtIdPerfilIdoneo = new javax.swing.JTextField();
        buttonBuscarHamming = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCandidatos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jMenuItem1.setText("VER EVALUACIÓN");
        jMenuItem1.setActionCommand("VER EVALUACIÓN");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUSQUEDA Y SELECCIÓN DE CANDIDATOS");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda de Candidatos"));
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N

        txtIdPerfilIdoneo.setName(""); // NOI18N
        txtIdPerfilIdoneo.setOpaque(false);
        txtIdPerfilIdoneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPerfilIdoneoActionPerformed(evt);
            }
        });

        buttonBuscarHamming.setText("BUSCAR Y SELECCIONAR CANDIDATOS");
        buttonBuscarHamming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarHammingActionPerformed(evt);
            }
        });

        jLabel1.setText("ID PERFIL IDÓNEO");

        jLabel3.setText("ID PUESTO");

        jLabel4.setText("DESCRIPCIÓN PERFIL");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("FECHA DE VIGENCIA");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("FECHA DE ALTA ");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setText("ESTATUS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(381, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPerfilIdoneo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBuscarHamming)
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPerfilIdoneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(buttonBuscarHamming, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tableCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableCandidatos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tableCandidatos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("CANDIDATOS ENCONTRADOS DE ACUERDO AL PERFIL IDÓNEO");

        jButton3.setText("REGRESAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBusquedaCandidatos().setVisible(true);
            }
        });
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//         JOptionPane.showMessageDialog(null, "Debe introducir un ID");
   
    int fila = tableCandidatos.getSelectedRow();          
    String idCandidato = tableCandidatos.getValueAt(fila, 0).toString();            
    int idPerfilIdoneo = Integer.parseInt(tableCandidatos.getValueAt(fila, 1).toString());            
    String metMedida   = tableCandidatos.getValueAt(fila, 2).toString();            

    if (fila >= 0)
    {
       VentanaPerfilesCandidatosEncontrados perfilesCandidatosEnc = new VentanaPerfilesCandidatosEncontrados();
       perfilesCandidatosEnc.setVisible(true);
      
       int IdPerfilIdoneo = Integer.parseInt(tableCandidatos.getValueAt(fila, 0).toString() );    
       
       perfilesCandidatosEnc.mostrarDatos(idCandidato,idPerfilIdoneo,metMedida);
               
          
       dispose();        
    }
    else
    {
      JOptionPane.showMessageDialog(null, "Debes seleccionar una Perfil");                
    }
        
    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void buttonBuscarHammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarHammingActionPerformed


     String idPuestoTI = jTextField1.getText();
     Date fechaVigencia = Date.valueOf(jTextField4.getText());
     String estatusCarac = jTextField5.getText();

     int numReg = 0;
     int idPerfilIdoneo = Integer.parseInt(txtIdPerfilIdoneo.getText());
     Conexion c = new Conexion();
     Connection con = c.getConexion();
     String sql_1 = "SELECT * FROM Puestos_TI_cand WHERE Id_puesto ='"+ idPuestoTI +"'";
            
     try {            
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(sql_1);

         
         while(rs.next())
         {                     
          String idCandidato = rs.getString(1);
          System.out.println("***** CANDIDATO ********* : " + idCandidato);
          
          PerfilesCandidatosAlta perfilesCand = new PerfilesCandidatosAlta();

          // INSERT TABLA: Perfiles_candidatos_general 
          perfilesCand.altaPerfilCandidatoGen(idCandidato, idPerfilIdoneo, fechaVigencia, estatusCarac);
          // INSERT TABLA: Perfiles_candidatos_detalle
          perfilesCand.altaPerfilCandidatoDet(idCandidato, idPerfilIdoneo, idPuestoTI);

         // Obtiene las medidas de distancia (Hamming, Euclidiana, Russel -Rao y Jaccard) y las actualiza en la tabla: Perfiles_candidatos_general
         MedidasDistancia medidasDistancia = new MedidasDistancia();
         medidasDistancia.obtieneMedidaDistancia(idPerfilIdoneo, idCandidato);
            
                     
          numReg ++;
         }
         
         rs.close();
         con.close();
       
         if (numReg == 0)
            {
            JOptionPane.showMessageDialog(null, "No se encontraron resultados.\nIntente nuevamente");     
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaCandidatosInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        c.cerrarConexion();
        mostrarDatos(idPerfilIdoneo);
        
                   
        


    }//GEN-LAST:event_buttonBuscarHammingActionPerformed

    private void txtIdPerfilIdoneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPerfilIdoneoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPerfilIdoneoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       VentanaPerfilesIdoneosPrincipal perfilesIdoneos = new VentanaPerfilesIdoneosPrincipal();
       perfilesIdoneos.setVisible(true);
      
       perfilesIdoneos.mostrarDatos("");
             
       dispose();        

    }//GEN-LAST:event_jButton3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarHamming;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tableCandidatos;
    private javax.swing.JTextField txtIdPerfilIdoneo;
    // End of variables declaration//GEN-END:variables

    
}
